CREATE TABLE IF NOT EXISTS client(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(200) NOT NULL CHECK(LENGTH(name) >=3)
);

CREATE TABLE IF NOT EXISTS planet(
ID VARCHAR(10) PRIMARY KEY CHECK (ID = UPPER(ID) AND ID ~ '[A-Z0-9]'),
name VARCHAR(500) NOT NULL CHECK(LENGTH(name) >=1)
);

CREATE TABLE IF NOT EXISTS ticket(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  client_id INT,
  from_planet_id VARCHAR(10),
  to_planet_id VARCHAR(10),
  FOREIGN KEY (client_id) REFERENCES client(ID),
  FOREIGN KEY (from_planet_id) REFERENCES planet(ID),
  FOREIGN KEY (to_planet_id) REFERENCES planet(ID)
);